# config file for snakemake


INDIR: "/data3/projects/xanthopore/baotram/test/reads" #"/scratch/baotram/test/reads", "/home/baotram/tal/workflow/test/reads", "/data3/projects/xanthopore/baotram/test/reads"
0UTDIR: "/data3/projects/xanthopore/baotram/test/results_scratch" # "/scratch/baotram/test/results", "/home/baotram/tal/workflow/test/results"



NASID: 'nas3'

KIT: "SQK-RBK004"
FLOWCELL: "FLO-MIN106"
# THREADS: 12

RESOURCE: 'GPU' # "CPU"/"GPU"
NUM_GPUS: 3 # GPU mode only

GUPPY_BASECALLER:
    'MIN_QSCORE': 7
    'NUM_CALLERS': 6 # recommended: NUM_CALLERS=2*NUM_GPUS
    'CPU_PER_CALLER': 12
    'GPU_PER_DEVICE': 4
    'ADDITION': '--hp_correct true' # additional params that do not affect output format or other rules


DEMULTIPLEXER: ["guppy", "deepbinner"]

GUPPY_BARCODER:
    'CONFIG': "configuration.cfg"
    'WORKER_THREADS': 8
    'ADDITION': ''

DEEPBINNER_CLASSIFY:
    'PRESET': 'rapid' # 'native'/'rapid'
    'OMP_NUM_THREADS': 12 # GPU mode only, recommended: OMP_NUM_THREADS=2*NUM_GPUS
    'ADDITION': ''

MINIONQC:
    'QSCORE_CUTOFF': 7
    'SMALLFIGURES': 'FALSE' # 'TRUE'/'FALSE'
    'PROCESSORS': 12
    'FIG': ["channel_summary", "flowcell_overview", "gb_per_channel_overview", "length_by_hour", "length_histogram", "length_vs_q", "q_by_hour", "q_histogram", "reads_per_hour", "yield_by_length", "yield_over_time"]

ONT_FAST5_API:
    'THREADS': 12
