# config file for snakemake
# adjust variables berfore running baseDmux workflow

##############################
##### input/output directory
INDIR: "/home/baotram/tal/workflow/test/reads" #"/scratch/baotram/test/reads", "/home/baotram/tal/workflow/test/reads", "/data3/projects/xanthopore/baotram/test/reads"
0UTDIR: "/home/baotram/tal/workflow/test" # "/scratch/baotram/test/results", "/home/baotram/tal/workflow/test/results", "/data3/projects/xanthopore/baotram/test/results_scratch_1303"
NASID: 'nas3' # host name, if indir and outdir in NAS but workdir is not 


##############################
##### kit and flowcell
KIT: "SQK-RBK004"
FLOWCELL: "FLO-MIN106"


##############################
##### resources
RESOURCE: 'GPU' # "CPU"/"GPU", resources for running Guppy and Deepbinner
NUM_GPUS: 3 # GPU mode only


##############################
##### guppy_basecaller parameters
GUPPY_BASECALLER:
    'MIN_QSCORE': 7 # threshold qscore for filtering
    'NUM_CALLERS': 6 # recommended: NUM_CALLERS=2*NUM_GPUS
    'CPU_PER_CALLER': 12
    'GPU_PER_DEVICE': 4 # GPU mode only
    'ADDITION': '--hp_correct true' # additional params that do not affect output format or other rules


##############################
##### choose types of demultiplexer
DEMULTIPLEXER: ["guppy", "deepbinner"] # "guppy"/"deepbinner"


##############################
##### guppy_barcoder parameters
GUPPY_BARCODER:
    'CONFIG': "configuration.cfg"
    'WORKER_THREADS': 8
    'ADDITION': ''


##############################
##### deepbinner classify parameters
DEEPBINNER_CLASSIFY:
    'PRESET': 'rapid' # 'native'/'rapid'
    'OMP_NUM_THREADS': 12 # GPU mode only, recommended: OMP_NUM_THREADS=2*NUM_GPUS
    'ADDITION': ''


##############################
##### MinIONQC parameters
MINIONQC:
    'QSCORE_CUTOFF': 7
    'SMALLFIGURES': 'FALSE' # 'TRUE'/'FALSE'
    'PROCESSORS': 12


##############################
##### multi_to_single_fast5 (ont_fast5_api) parameters
ONT_FAST5_API:
    'THREADS': 12
