# config file for snakemake
# adjust variables berfore running baseDmux workflow

##############################
##### input/output directory
INDIR: "/home/baotram/tal/workflow/test/reads" #"/scratch/baotram/test/reads", "/home/baotram/tal/workflow/test/reads", "/data3/projects/xanthopore/baotram/test/reads", "/data3/projects/xoogenomes/ONT_BAI3-talC_mutants/TalC_Muts_20190129/TalC_Muts"
OUTDIR: "/home/baotram/tal/workflow/test" # "/scratch/baotram/test/results", "/home/baotram/tal/workflow/test/results", "/data3/projects/xanthopore/baotram/test/results_scratch_1303"
NASID: '' # host name, if indir and outdir in NAS but workdir is not


##############################
##### kit and flowcell
KIT: "SQK-RBK004"
FLOWCELL: "FLO-MIN106"


##############################
##### resources
RESOURCE: 'GPU' # "CPU"/"GPU" ## resources for running Guppy and Deepbinner
NUM_GPUS: 3 # mumber of GPU devices to use # baseDmux will decide CUDA devices based on availability ## GPU mode only


##############################
##### guppy_basecaller parameters
GUPPY_BASECALLER:
    'MIN_QSCORE': 7 # basecalling will filter reads based on minimum q-score specified here
    'NUM_CALLERS': 6 # number of parallel basecallers to create ## recommended: NUM_CALLERS=2*NUM_GPUS
    'CPU_THREADS_PER_CALLER': 12 # number of CPU threads to create for each caller to use
    'GPU_RUNNERS_PER_DEVICE': 4 # number of neural network runners to create per CUDA device ## GPU mode only
    'ADDITION': '--hp_correct true' # additional params that do not affect output format ## provide parameters with arguments ## do NOT use --compress_fastq, because next steps use uncompressed fastq


##############################
##### choose types of demultiplexer
DEMULTIPLEXER: ["guppy", "deepbinner"] # "guppy"/"deepbinner"


##############################
##### guppy_barcoder parameters
GUPPY_BARCODER:
    'CONFIG': "configuration.cfg"
    'WORKER_THREADS': 12
    'ADDITION': ''


##############################
##### deepbinner classify parameters
DEEPBINNER_CLASSIFY:
    'PRESET': 'rapid' # 'native'/'rapid'
    'OMP_NUM_THREADS': 12 #
    'ADDITION': ''


##############################
##### MinIONQC parameters
MINIONQC:
    'QSCORE_CUTOFF': 7
    'SMALLFIGURES': 'FALSE' # 'TRUE'/'FALSE'
    'PROCESSORS': 12


##############################
##### multi_to_single_fast5 (ont_fast5_api) parameters
ONT_FAST5_API:
    'THREADS': 12

GET_READS_PER_GENOME:
    'BARCODE_BY_GENOME': '/home/baotram/tal/workflow/test/reads/barcodeByGenome_sample.tsv'
    'TRANSFERING': 'copy'
