# config file for snakemake to run wo


DIR: "/scratch/baotram/test/"


SINGULARITY:
    'GUPPY': "container/new.simg" # guppy + miniconda
    'DEEPBINNER': "container/deepbinner.simg" # deepbinner + ont_fast5_api + python3
    'ALL': "" #"cpu-py3-tsrf.simg"


CONDA:
    'MINIONQC': "conda/conda_minionqc.yaml"
    'MULTIQC': "conda/conda_multiqc.yaml"

QSCORE_CUTOFF: 7

BASECALLER:
    'RESOURCE': 'cpu' # or 'gpu'
#    'CONFIG': "dna_r9.4.1_450bps_fast.cfg"
    'NUM_CALLERS': 4
    'MIN_QSCORE': 7
    'HP_CORRECT': 'true'
    'ENABLE_TRIMMING': 'true'
    'CPU_PER_CALLER': 1
    'GPU_PER_DEVICE': 1
    'CUDA': "auto"

KIT: "SQK-RBK004"
FLOWCELL: "FLO-MIN106"
THREADS: 4

DEMULTIPLEXER: ["guppy", "deepbinner"]
DEMULTIPLEXING_CONFIG: "configuration.cfg"
