channels:
    - bioconda
    - conda-forge
    - r
    - defaults
    - biobuilds
dependencies:
    - r-base=3.5.0
    - r-essentials=3.5.0=r350_0
    - mkl-service=2.3.0
    - xorg-libxrender=0.9.10
    - fonts-conda-forge
